Adding picplace example app
reddit/devvit-sandbox pull request #1
Opened 2023-04-06 17:43 UTC by ryanmurakami

Closes # 

## 💸 TL;DR

## 📜 Details
[Design Doc]()

[Jira]()

## 🧪 Testing Steps / Validation

## ✅ Checks

- [ ] CI tests (if present) are passing
- [ ] Adheres to code style for repo
- [ ] Contributor License Agreement (CLA) completed if not a Reddit employee

2023-04-14 19:54 UTC, sp3nx0r commented on picplace/package.json
> +    "@devvit/protos": "0.8.12-next-2023-04-03-d4cc700c.0",
can you update to public devvit deps

2023-04-14 19:54 UTC, sp3nx0r commented on picplace/yarn.lock
> +"@devvit/plugins@0.8.12-next-2023-04-03-d4cc700c.0":
also you'll likely want to relock without our internal registry in the mix

2023-04-14 19:54 UTC, sp3nx0r requested changes
two asks for ya

2023-04-17 22:21 UTC, ryanmurakami commented
Updated deps & registry

2023-04-18 13:35 UTC, sp3nx0r approved these changes
:fish:

2023-04-18 15:58 UTC, merged